### ISSUE TITLE
`rust-esplora-client` shouldn't introduce an async runtime

### ISSUE THREAD

**Issue by tnull** [bitcoindevkit/rust-esplora-client#102]
In #98, a dependency on the `async_std` runtime was introduced. IIUC, this was done *only* to use its `sleep` method.

I don't think `rust-esplora-client` should make choices regarding which async runtime users should use. If anything, it should be using the by now default `tokio` rather than `async_std`.

I believe I already brought this up in the discussion of the precursor #71, which however seems now gone for some reason.

An alternative to pulling in an extra dependency for this would simply be to have the user specify a `sleep` callback function that would use whatever sleep functionality they have available in their runtime.

(cc @notmandatory @ValuedMammal)

**Comment by ValuedMammal** [comment]
Thanks for raising the issue @tnull
